// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjO5eJJca1dgc4-uIT41NvFmtUqhhupAc',
    appId: '1:207851949341:web:e4e509bbfbd2335489a5f4',
    messagingSenderId: '207851949341',
    projectId: 'fluxfoot-652d2',
    authDomain: 'fluxfoot-652d2.firebaseapp.com',
    storageBucket: 'fluxfoot-652d2.firebasestorage.app',
    measurementId: 'G-7R4DBMBQ39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXcfTOxa1m8w3ZfyfBWnQslRWxJIzhawU',
    appId: '1:207851949341:android:63bf413180ce97f789a5f4',
    messagingSenderId: '207851949341',
    projectId: 'fluxfoot-652d2',
    storageBucket: 'fluxfoot-652d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9pbuQ7leSnT5QhJPg6hWhXAe1s3yM-U',
    appId: '1:207851949341:ios:ecd4b756b999ea3f89a5f4',
    messagingSenderId: '207851949341',
    projectId: 'fluxfoot-652d2',
    storageBucket: 'fluxfoot-652d2.firebasestorage.app',
    iosBundleId: 'com.example.fluxfootSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr9pbuQ7leSnT5QhJPg6hWhXAe1s3yM-U',
    appId: '1:207851949341:ios:ecd4b756b999ea3f89a5f4',
    messagingSenderId: '207851949341',
    projectId: 'fluxfoot-652d2',
    storageBucket: 'fluxfoot-652d2.firebasestorage.app',
    iosBundleId: 'com.example.fluxfootSeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjO5eJJca1dgc4-uIT41NvFmtUqhhupAc',
    appId: '1:207851949341:web:10eebdde0b49271889a5f4',
    messagingSenderId: '207851949341',
    projectId: 'fluxfoot-652d2',
    authDomain: 'fluxfoot-652d2.firebaseapp.com',
    storageBucket: 'fluxfoot-652d2.firebasestorage.app',
    measurementId: 'G-78PS336CS6',
  );
}
